; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main
description = Project for my Wearable Electronics Gadget

; Common ESP32 settings - inherit from this
[esp32_common]
platform = https://github.com/tasmota/platform-espressif32.git
board = adafruit_feather_esp32c6
framework = arduino
monitor_speed = 115200
;build_flags = 
;    -D ARDUINO_USB_CDC_ON_BOOT=1
;    -D ARDUINO_USB_MODE=1
;    -D CONFIG_ARDUINO_USB_CDC_ENABLED=1
;    -D ARDUINO_ADAFRUIT_FEATHER_ESP32C6
lib_deps = 
    adafruit/Adafruit BME280 Library @ ^2.2.2
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    SD @ ^3.3.0
	fbiego/ESP32Time @ ^2.0.6
    WiFi
test_framework = unity
build_flags = -I include
build_src_filter = ; pls note that the src is not compiled for a test
    +<*> ; Makes sure the src directory is included in the build path
    -<../lib/**/example/*>
    +<../lib/src/*>
extra_scripts = post:scripts/auto_monitor.py

[env:main]
extends = esp32_common
test_filter = test_embedded
build_flags = 
    ${esp32_common.build_flags} ; Keeps the build flags from esp32_common
    -Itest/test_embedded/includes
    -Itest/test_service/includes    ; only needed for the service environment. TODO Remove this later

[env:service]
; Environment to test Services
extends = esp32_common
test_filter = test_service
build_flags = 
    ${esp32_common.build_flags} ; Keeps the build flags from esp32_common
    -Itest/test_service/includes
    


[env:native]
platform = native
test_filter = test_native


; Display Example
[env:display]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/display_manager/example/example_display/src/main.cpp>

[env:sd]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/storage_manager/example/main.cpp>

[env:mock]
platform = native
test_filter = test_mock
build_flags = 
    -DMOCK
    -std=c++11
    -I include
    -I test/test_mock/include
build_src_filter = 
    +<*>
    -<main.cpp>
    -<utils/I2CScanner/*>
    -<utils/utils.cpp>
lib_ignore = 
    I2CScanner
test_build_src = no