; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main
description = Project for my Wearable Electronics Gadget

; Common ESP32 settings - inherit from this
[esp32_common]
platform = https://github.com/tasmota/platform-espressif32.git
board = adafruit_feather_esp32c6
framework = arduino
monitor_speed = 115200
board_build.partitions = ota_4mb.csv
lib_deps = 
    adafruit/Adafruit BME280 Library @ ^2.2.2
    adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
    adafruit/Adafruit MAX1704X @ ^1.0.0
    h2zero/NimBLE-Arduino @ ^2.5.0
    SD @ ^3.3.0
	fbiego/ESP32Time @ ^2.0.6
    WiFi
    ayushsharma82/ElegantOTA@^3.1.6
    ESP32Async/AsyncTCP@^3.4.9
    ESP32Async/ESPAsyncWebServer@^3.9.2
test_framework = unity
lib_ldf_mode = deep
lib_extra_dirs = 
    lib/hardware/
    lib/services/
build_flags = 
    -I include
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1
build_src_filter = ; pls note that the src is not compiled for a test
    +<*> ; Makes sure the src directory is included in the build path
    -<../lib/**/example/*>
    +<../lib/src/*>
extra_scripts = post:scripts/auto_monitor.py

[env:main]
extends = esp32_common
test_filter = test_hardware
build_flags = 
    ${esp32_common.build_flags}
    -Itest/test_hardware/includes
    -Itest/test_service/includes    ; only needed for the service environment. TODO Remove this later
build_src_filter = 
    +<*> 
    -<../lib/**/example/*>
    +<../lib/src/*>
    -<hardware_test.cpp>

[env:service]
; Environment to test Services
; Reads Sensor Data and Plots it on the screen.
extends = esp32_common
test_filter = test_service
build_flags = 
    ${esp32_common.build_flags}
    -Itest/test_service/includes

[env:hardware]
; Hardware test environment — unit tests + firmware for lowest-level HW exercise
extends = esp32_common
test_filter = test_hardware
build_flags = 
    ${esp32_common.build_flags}
    -Itest/test_hardware/includes



; Display Example
[env:display]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/hardware/display_manager/example/example_display/src/main.cpp>

[env:clock]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/services/display_service/example/example_clock/src/main.cpp>

[env:sd]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/hardware/storage_manager/example/main.cpp>

[env:sd_read]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/hardware/storage_manager/example/read_all.cpp>

[env:sd_delete]
extends = esp32_common
build_src_filter = 
    -<*> ; exclude everything from src
    +<${PROJECT_DIR}/lib/hardware/storage_manager/example/delete_all.cpp>

[env:mock]
platform = native
test_filter = test_mock
test_framework = unity
lib_ldf_mode = deep
lib_extra_dirs = 
    lib/hardware/
    lib/services/
build_flags = 
    -DMOCK
    -std=c++11
    -I include
    -I test/test_mock/include
build_src_filter = 
    +<*>
    -<main.cpp>
    -<hardware_test.cpp>
    -<utils/I2CScanner/*>
    -<utils.cpp>
lib_ignore = 
    I2CScanner
    test_runner
    display_manager
test_build_src = no